// <auto-generated />
using System;
using Card_Game_Database_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Card_Game_Database_Website.Migrations
{
    [DbContext(typeof(TradingCardContext))]
    partial class TradingCardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Card_Game_Database_Website.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"), 1L, 1);

                    b.Property<string>("CardAttack1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttack2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttackCost1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttackCost2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttackDamage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttackDamage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttackEffect1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttackEffect2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttackValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardAttribute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardDefenseValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardHP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardMonsterLevel")
                        .HasColumnType("int");

                    b.Property<string>("CardMonsterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardRetreatCost")
                        .HasColumnType("int");

                    b.Property<string>("CardRuleBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
